version: '3'
services:
  postgresql:
    image: 'postgres:12.3'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cursos_pra_todos
    ports:
      - '5432:5432'
